### ISSUE TITLE
Upload Method with VueJS

### ISSUE THREAD

**Issue by tbenoist1** [juanchinovas/nativescript-google-drive#2]
Hello,

I tried to implement the upload method on a nativescript-vue project.
onUploadFile(fileInfo, name) { fileInfo.name = name; this.driveHelper.uploadFile(fileInfo); },
when I call it I don't have any error message but it doesn't appear in my drive. Have I missed something ?

**Comment by tbenoist1** [comment]
Hello,

I tried to implement the upload method on a nativescript-vue project. 
`            onUploadFile(fileInfo, name) {
                fileInfo.name = name;
                this.driveHelper.uploadFile(fileInfo);
            }, `
when I call it I don't have any error message but it doesn't appear in my drive. Have I missed something ?

**Comment by juanchinovas** [comment]
Hi!,

@tbenoist1 thanks for report this issue, it was fixed in the version 1.0.3.
